### ISSUE TITLE
modeltranslation 0.19.3+ with Django CMS 4.1.x - CMS Plugin functionalities broken

### ISSUE THREAD

**Issue by aacimov** [deschler/django-modeltranslation#748] opened 2024-07-17 09:55 UTC
As stated in Django CMS issue tracker: https://github.com/django-cms/django-cms/issues/7948

Django CMS 4.1.x with modeltranslation active - custom CMS plugin attributes `allow_children`, and `child_classes` do not work correctly.

Each plugin that has `allow_children` has the ability to add child plugins but they are locked (one is not able to add plugins to children even though the `allow_children` with `child_classes` is set on Column in this example).

On the other hand, plugins that do not have explicitly set the `allow_children` attribute still have the ability to add children which is wrong.

**Image 1 - working example** with modeltranslation 0.19.2 - Text plugin has the **+ sign disabled** which is expected, and the Column plugins have the **+ sign enabled** which is expected:

<img width="398" alt="working 0 9 12" src="https://github.com/user-attachments/assets/560f1a2e-947b-4092-92e4-378fbf453d9c">

**Image 2 - not working example** with modeltranslation 0.19.3 and above - Text plugin has the **+ sign enabled** which is not expected, and the Column plugins have the **lock sign** which is not expected since no other plugins can be added into it:

<img width="398" alt="not_working 0 9 13" src="https://github.com/user-attachments/assets/92441d18-787f-40bc-a35a-894c17691a57">

## Project environment variables

- Django 4.2.13
- django_modeltranslation 0.19.2 (tried 0.19.3 and above which are not working, lower versions do work correctly)
- django-cms 4.1.1
- Python 3.10

**Comment by aacimov** [comment] 2024-07-17 20:41
Just tested with django-cms 3.11.x - affected as well.

**Comment by last-partizan** [comment] 2024-07-18 08:16
Hello.

Are you sure version 0.19.0 is working? because i there isn't much changes. But jump from 0.18 to 0.19 included some relatively big changes.

If you have time, please do additional testing using git version and `git bisect`.

**Comment by aacimov** [comment] 2024-07-19 08:48
@last-partizan yes, everything below 0.19.3 is working as expected. I will look into it over weekend probably and let you know.

**Comment by benzkji** [comment] 2024-07-22 21:19
for me as well, it is `django-modeltranslation<0.19.3` that works.

**Comment by benzkji** [comment] 2024-07-22 21:22
0.9.13 introduces changes on the admin clasess, that is what the cms uses, it makes sense to me.

**Comment by last-partizan** [comment] 2024-07-23 11:30
Yeah, there's some changes in admin, but they're mostly related to typing support.

If someone can provide repo with minimal reproduction, i can look into this.

**Comment by MacLake** [comment] 2024-08-03 16:33
I can confirm it, 0.19.2 works, and 0.19.3 introduces the bug in both django-cms 3.11.6 and 4.1.2.

**Comment by MacLake** [comment] 2024-08-06 19:46
So here is a minimal repo for reproducing the issue: I have added modeltranslation to django-cms-quickstart and published a fork here:

https://github.com/MacLake/django-cms-quickstart/tree/modeltranslation. Follow the instructions to get the project running.

First add a plugin that can contain other plugins, e. g. a Jumbotron, at top level. You can add a text plugin. to the Jumotron.

Then add a container, add a Jumbotron to the container. Now you can’t add a text or any other plugin to this Jumbotron, as it is locked. This is caused by modeltranslation>=0.19.3.

**Comment by benzkji** [comment] 2024-08-07 07:42
there is some background info in #745. It seems hidden and complicated.

**Comment by benzkji** [comment] 2024-08-13 14:18
I think I found the problem. Dict access of a admin class that inherits from a TranslationAdmin is possible, and doesn't throw any error.

```
class MyTranslationAdmin(TranslationAdmin):
    my_prop = "123"

MyTranslationAdmin["123"]  # returns that class itself!
```

Also, a PR that shows that: https://github.com/deschler/django-modeltranslation/pull/749

**Comment by benzkji** [comment] 2024-09-03 12:02
#755 resolves this problem for me.

**Comment by last-partizan** [comment] 2024-09-04 16:38
Thanks for testing, merged and released.

**Comment by benzkji** [comment] 2024-09-05 05:42
Thanks!

**Closed** 2024-11-10 09:21 UTC
