### ISSUE TITLE
_base_manager shouldn't be MultilingualManager?

### ISSUE THREAD

**Issue by huaying** [deschler/django-modeltranslation#497] opened 2019-03-05 21:50 UTC
I just found the below code show the error: 
`django.db.utils.IntegrityError: (1062, "Duplicate entry 'xxx' for key 'PRIMARY'")`

```
class MyManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_hidden=False)

class MyModel(models.Model):
    objects = MyManager()

item = MyModel.objects.create(is_hidden=True)
item.is_hidden = False
item.save()
```

It seems that the `save` method calls the default manager, and I just checked the django code and found the error is due to the override of the _base_manager. It's doing the query with `MultilingualQuerySet` which is using my custom query set.

https://github.com/django/django/blob/master/django/db/models/base.py#L841

Any suggestion?

**Comment by last-partizan** [comment] 2019-03-05 22:04
can you show a bit more code?

**Comment by last-partizan** [comment] 2019-03-05 22:17
Take a look at test in 471-test-hidden branch.

I can not reproduce this behaviour.

**Comment by huaying** [comment] 2019-03-05 23:18
Hi, I think you might need to customize the manager first. 

When we execute the `save`,  it uses `_base_manager` to update the object. I assume `_base_manager` is overridden with `MultilingualManager` which is using MyManager? 

Then it couldn't find the object becuase `super().get_queryset().filter(is_hidden=False)`

**Comment by last-partizan** [comment] 2019-03-06 07:50
https://github.com/deschler/django-modeltranslation/blob/b4705173316fdda7e33390a01440f8b4ac0e38ed/modeltranslation/tests/models.py#L409-L420

take a look, here we are customizing manager
then

https://github.com/deschler/django-modeltranslation/blob/b4705173316fdda7e33390a01440f8b4ac0e38ed/modeltranslation/tests/tests.py#L2734-L2740

**Comment by mes3yd** [comment] 2019-05-02 14:52
Dupe of https://github.com/deschler/django-modeltranslation/issues/455

**Closed** 2019-08-05 15:58 UTC
