### ISSUE TITLE
Filtering a boolean field

### ISSUE THREAD

**Issue by itwy** [deschler/django-modeltranslation#376] opened 2016-06-11 00:06 UTC
Is this really needed:

```
    categories = Category.objects.filter(**{
        'is_visible_' + request.LANGUAGE_CODE: True
    })
```

If I use 'is_visible' it's using English all the time despite having the current language set to French. Why is that?

**Comment by zlorf** [comment] 2016-06-11 08:04
Can you please post the model definition and its `TranslationOptions`?

**Comment by madEng84** [comment] 2016-06-11 08:10
Why do you want to filter in this manner?
If you want to filter in the current active language you have only to do:
.filter(is_visible=True)
Otherwise, if you are in english but you want to filter for french visible fields you have to include your django query in a withblock activate('fr'):

**Comment by zlorf** [comment] 2016-06-11 08:16
As I understand, `.filter(is_visible=True)` is not working as intended for @itwy. Maybe language detection is not working?
Can you print `request.LANGUAGE_CODE` and `Category.objects.__class__.__mro__` just before the query?
And also please provide mandatory info: Django and MT version.

**Comment by zlorf** [comment] 2016-08-21 19:36
@itwy , closing as no feedback was provided. Please reopen with more info if problem persists.

**Closed by zlorf** 2016-08-21 19:36 UTC
