### ISSUE TITLE
Using `.full_clean` with fallback languages on instance before saving leads to updating incorrect fields.

### ISSUE THREAD

**Issue by sdeprez** [deschler/django-modeltranslation#382] opened 2016-08-12 16:31 UTC
First of all, thanks for your work, amazing library! 

Otherwise, I'm facing the following issue. Let's say we have the model:

```
from django.db import models

class MyObject(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
```

with the settings

```
LANGUAGES = [ 
    ('en', _('English')),
    ('fr', _('French')),
]
MODELTRANSLATION_FALLBACK_LANGUAGES = ('en', 'fr')
```

And we execute the following code:

```
my_object = MyObject.objects.create()

# Assign a value ONLY to name_fr
my_object.name_fr  = 'some_fr_name'

# Here is the line that causes the problem!
my_object.full_clean()
my_object.save()

#
my_object.refresh_from_db()
print my_object.name_en   # print 'some_fr_name'!
```

So the problem is that `name_en` is updated even if we only specify the value of `name_fr`! If you remove the French from fallback values, or if you don't do the full clean, it works fine. It also works fine if `name_en` had a value before.

**Comment by zlorf** [comment] 2016-08-21 19:35
Interesting, will take a look in following days.

**Comment by rcatajar** [comment] 2017-08-30 14:38
@zlorf @deschler Issue is still present on the latest version. 

translation.py
```python

class TestObjectTO(TranslationOptions):
    fields = ('test', )


translator.register(TestObject, TestObjectTO)
```

models.py
```python
class TestObject(models.Model):
    test = models.CharField(max_length=100)
```

settings.py
```python

LANGUAGE_CODE = 'en'
LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French'))
)
MODELTRANSLATION_LANGUAGES = ('en', 'fr')
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_FALLBACK_LANGUAGES = ('en', 'fr')
```

test shell:
```python
In [2]: obj = TestObject.objects.create()

In [3]: obj.test_fr = "foobar"

In [4]: obj.test_en

In [5]: obj.full_clean()

In [6]: obj.test_en
Out[6]: 'foobar'

In [7]: obj.save()

In [8]: obj.refresh_from_db()

In [9]: obj.test_en
Out[9]: 'foobar'
```

Any idea what can be the root cause ? I'm not familiar with the source code, but I'm willing to take time to submit a PR if you can point me to the right direction.

**Comment by buczek** [comment] 2020-01-08 14:40
This is caused by the the field validation of django

https://github.com/django/django/blob/07f6ff09e431cec48be5e46d843a4bbf10bfeac6/django/db/models/base.py#L1226:

```python
def clean_fields(self, exclude=None):
...
    for f in self._meta.fields:
            if f.name in exclude:
                continue
            # Skip validation for empty fields with blank=True. The developer
            # is responsible for making sure they have a valid value.
            raw_value = getattr(self, f.attname)
            if f.blank and raw_value in f.empty_values:
                continue
            try:
                setattr(self, f.attname, f.clean(raw_value, self))
```

Applied to the "test shell" code from the previous comment:

When `obj.test_fr = "foobar"` is set, then `obj.test` is set along with it. When above validation code tries to validate the `obj.test` field, it reads `"foobar"` into `raw_value`. This isn't blank and so `setattr(self,"test","foobar")` is called. This has no effect on `obj.test`, but `obj.test_en` is set along with it, if "en" is the current language.

**Comment by last-partizan** [comment] 2020-01-13 07:37
Any ideas how this can be fixed?

**Comment by buczek** [comment] 2020-01-14 11:50
Disable the implicit setting of the translation field from the translated field ( Rule 2 of https://django-modeltranslation.readthedocs.io/en/latest/usage.html#rules-for-translated-field-access ) if we come from `clean_fields` ?

The patch below seems to work for me.

```
diff --git a/lib/python3.7/site-packages/modeltranslation/fields.py b/lib/python3.7/site-packages/modeltranslation/fields.py
index d3c5a42..2ff0d83 100644
--- a/lib/python3.7/site-packages/modeltranslation/fields.py
+++ b/lib/python3.7/site-packages/modeltranslation/fields.py
@@ -314,7 +314,7 @@ class TranslationFieldDescriptor(object):
         instance.__dict__[self.field.name] = value
         if isinstance(self.field, fields.related.ForeignKey):
             instance.__dict__[self.field.get_attname()] = None if value is None else value.pk
-        if getattr(instance, '_mt_init', False):
+        if getattr(instance, '_mt_init', False) or getattr(instance, '_mt_disable', False):
             # When assignment takes place in model instance constructor, don't set value.
             # This is essential for only/defer to work, but I think it's sensible anyway.
             return
diff --git a/lib/python3.7/site-packages/modeltranslation/translator.py b/lib/python3.7/site-packages/modeltranslation/translator.py
index 901f701..65635d0 100644
--- a/lib/python3.7/site-packages/modeltranslation/translator.py
+++ b/lib/python3.7/site-packages/modeltranslation/translator.py
@@ -267,7 +267,9 @@ def patch_clean_fields(model):
                 if orig_field_name in exclude:
                     field.save_form_data(self, value, check=False)
             delattr(self, '_mt_form_pending_clear')
+        setattr(self, '_mt_disable', True)
         old_clean_fields(self, exclude)
+        setattr(self, '_mt_disable', False)
     model.clean_fields = new_clean_fields
```

**Comment by buczek** [comment] 2020-01-15 08:17
Maybe better to use `finally` to reset the flag in case of unhandled expections.

```
From 8fa955600d5653af7ee0c552fb18005a0dd9e043 Mon Sep 17 00:00:00 2001
From: Donald Buczek <buczek@molgen.mpg.de>
Date: Mon, 13 Jan 2020 16:43:34 +0100
Subject: [PATCH] modeltranslations: Don't leak into current language

Disable the implicit setting of the translation field from
the translated field ( Rule 2 of [1] ) if we come from
clean_fields. See [2]

[1] https://django-modeltranslation.readthedocs.io/en/latest/usage.html#rules-for-translated-field-access ) if we come from clean_fields
[2] https://github.com/deschler/django-modeltranslation/issues/382
---
 lib/python3.7/site-packages/modeltranslation/fields.py     | 2 +-
 lib/python3.7/site-packages/modeltranslation/translator.py | 6 +++++-
 2 files changed, 6 insertions(+), 2 deletions(-)

diff --git a/lib/python3.7/site-packages/modeltranslation/fields.py b/lib/python3.7/site-packages/modeltranslation/fields.py
index d3c5a42..2ff0d83 100644
--- a/lib/python3.7/site-packages/modeltranslation/fields.py
+++ b/lib/python3.7/site-packages/modeltranslation/fields.py
@@ -314,7 +314,7 @@ class TranslationFieldDescriptor(object):
         instance.__dict__[self.field.name] = value
         if isinstance(self.field, fields.related.ForeignKey):
             instance.__dict__[self.field.get_attname()] = None if value is None else value.pk
-        if getattr(instance, '_mt_init', False):
+        if getattr(instance, '_mt_init', False) or getattr(instance, '_mt_disable', False):
             # When assignment takes place in model instance constructor, don't set value.
             # This is essential for only/defer to work, but I think it's sensible anyway.
             return
diff --git a/lib/python3.7/site-packages/modeltranslation/translator.py b/lib/python3.7/site-packages/modeltranslation/translator.py
index 901f701..d58dd55 100644
--- a/lib/python3.7/site-packages/modeltranslation/translator.py
+++ b/lib/python3.7/site-packages/modeltranslation/translator.py
@@ -267,7 +267,11 @@ def patch_clean_fields(model):
                 if orig_field_name in exclude:
                     field.save_form_data(self, value, check=False)
             delattr(self, '_mt_form_pending_clear')
-        old_clean_fields(self, exclude)
+        setattr(self, '_mt_disable', True)
+        try:
+            old_clean_fields(self, exclude)
+        finally:
+            setattr(self, '_mt_disable', False)
     model.clean_fields = new_clean_fields
 
 
-- 
2.24.1

**Comment by last-partizan** [comment] 2020-01-15 08:20
@buczek Can you make a pull-request?

**Comment by buczek** [comment] 2020-01-15 15:05
Sure. Will do.

**Comment by last-partizan** [comment] 2020-01-16 11:18
Thanks to @buczek, this is now fixed :)

Released new version.

**Closed** 2020-01-16 11:18 UTC
